[settings]
mouse_mode = true
data_compact_columns = true
data_row_spacer = false

[db]

[keybindings.Menu]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-[>" = "CycleFocusBackwards"
"<Alt-]>" = "CycleFocusForwards"
"<Alt-\\>" = "FocusEditor"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Editor]
"<Ctrl-Enter>" = "SubmitEditorQuery"
"<Alt-Enter>" = "SubmitEditorQueryBypassParser"
"<Alt-[>" = "CycleFocusBackwards"
"<Alt-]>" = "CycleFocusForwards"
"<Alt-\\>" = "FocusEditor"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.History]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-[>" = "CycleFocusBackwards"
"<Alt-]>" = "CycleFocusForwards"
"<Alt-\\>" = "FocusEditor"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Data]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-[>" = "CycleFocusBackwards"
"<Alt-]>" = "CycleFocusForwards"
"<Alt-\\>" = "FocusEditor"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Favorites]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Alt-[>" = "CycleFocusBackwards"
"<Alt-]>" = "CycleFocusForwards"
"<Alt-\\>" = "FocusEditor"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.PopUp]
"<Ctrl-c>" = "Quit"
